import {
  ShoppingCart,
  Battery,
  Feather,
  Shield,
  Wrench,
  GripVertical,
  Map,
  Bomb,
  Skull,
  Radio,
  ZapOff,
  Syringe,
  Cross,
  Utensils,
  Hammer,
  Sword,
  Gem,
  BatteryCharging,
  Footprints,
  Maximize,
  Hand,
  Dumbbell,
  HeartPulse,
  TimerOff,
  Search,
  type LucideIcon,
  BowArrow,
  PaintBucket
} from 'lucide-react'

/**
 * Maps purchased item names from the game to their corresponding Lucide icons.
 * Used to display appropriate visual indicators for different item types in the UI.
 *
 * @constant {Record<string, LucideIcon>}
 *
 */
export const PURCHASED_ITEMS_ICON: Record<string, LucideIcon> = {
  'Cart Medium': ShoppingCart,
  'Cart Small': ShoppingCart,
  'Drone Battery': Battery,
  'Drone Feather': Feather,
  'Drone Indestructible': Shield,
  'Drone Torque': Wrench,
  'Drone Zero Gravity': GripVertical,
  'Extraction Tracker': Map,
  'Grenade Duct Taped': Bomb,
  'Grenade Explosive': Bomb,
  'Grenade Human': Skull,
  'Grenade Shockwave': Radio,
  'Grenade Stun': ZapOff,
  'Gun Handgun': BowArrow,
  'Gun Shotgun': BowArrow,
  'Gun Tranq': Syringe,
  'Health Pack Large': Cross,
  'Health Pack Medium': Cross,
  'Health Pack Small': Cross,
  'Melee Baseball Bat': Sword,
  'Melee Frying Pan': Utensils,
  'Melee Inflatable Hammer': Hammer,
  'Melee Sledge Hammer': Hammer,
  'Melee Sword': Sword,
  'Mine Explosive': Bomb,
  'Mine Shockwave': Bomb,
  'Mine Stun': Bomb,
  'Orb Zero Gravity': GripVertical,
  'Power Crystal': Gem,
  'Rubber Duck': Gem,
  'Upgrade Map Player Count': Map,
  'Upgrade Player Energy': BatteryCharging,
  'Upgrade Player Extra Jump': Footprints,
  'Upgrade Player Grab Range': Maximize,
  'Upgrade Player Grab Strength': Hand,
  'Upgrade Player Health': HeartPulse,
  'Upgrade Player Sprint Speed': Dumbbell,
  'Upgrade Player Tumble Launch': TimerOff,
  'Valuable Tracker': Search,
  'Duck Bucket': PaintBucket,
  'Cart Cannon': ShoppingCart,
  'Cart Laser': ShoppingCart,
  'Gun Laser': BowArrow,
  'Phase Bridge': GripVertical,
  'Upgrade Player Crouch Rest': Shield,
  'Upgrade Player Tumble Wings': Feather
}
